name: .NET

on:
  push:
  pull_request:

permissions:
  checks: write

jobs:
  build:
    name: ğŸ—ï¸ Build and test

    runs-on: ubuntu-latest

    env:
      TEST_RESULTS: ${{ github.workspace }}/.artifacts/test

    steps:
      - uses: actions/checkout@v6
        name: ğŸ›’ Checkout code
        with:
          filter: blob:none

      - name: ğŸ› ï¸ Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: ğŸ“¥ Restore dependencies
        run: dotnet restore -bl:${{ env.TEST_RESULTS }}/restore.binlog

      - name: ğŸ—ï¸ Build
        run: dotnet build -bl:${{ env.TEST_RESULTS }}/build.binlog

      - name: ğŸ§ª Test
        run: dotnet test -bl:${{ env.TEST_RESULTS }}/test.binlog --output Detailed --results-directory ${{ env.TEST_RESULTS }}

      - name: ğŸ“„ Publish test results
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: 'Test Results'
          path: ' ${{ env.TEST_RESULTS }}/*.trx'
          reporter: dotnet-trx

      - name: ğŸ“¤ Upload test artifacts
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: ${{ env.TEST_RESULTS }}
