name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: ğŸ—ï¸ Build and test

    runs-on: ubuntu-latest

    env:
      TEST_RESULTS: ${{ github.workspace }}/.artifacts/test

    steps:
      - uses: actions/checkout@v4
        name: ğŸ›’ Checkout code
        with:
          filter: blob:none

      - name: ğŸ› ï¸ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: ğŸ“¥ Restore dependencies
        run: dotnet restore -bl:${{ env.TEST_RESULTS }}/restore.binlog

      - name: ğŸ—ï¸ Build
        run: dotnet build -bl:${{ env.TEST_RESULTS }}/build.binlog

      - name: ğŸ§ª Test
        run: dotnet test -bl:${{ env.TEST_RESULTS }}/test.binlog

      - name: ğŸ“¤ Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: ${{ env.TEST_RESULTS }}
