name: .NET

on:
  push:
  pull_request:

permissions:
  checks: write

jobs:
  build:
    name: ðŸ—ï¸ Build and test

    runs-on: ubuntu-latest

    env:
      BINLOG_PATH: ${{ runner.temp }}/binlogs
      TESTRESULTS_PATH: ${{ runner.temp }}/testresults
      COVERAGEREPORT_PATH: ${{ runner.temp }}/coveragereports

    steps:
      - uses: actions/checkout@v6
        name: ðŸ›’ Checkout code
        with:
          filter: blob:none

      - name: ðŸ› ï¸ Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: ðŸ“¥ Restore dependencies
        run: dotnet restore -bl:${{ env.BINLOG_PATH }}/restore.binlog

      - name: ðŸ—ï¸ Build
        run: dotnet build -bl:${{ env.BINLOG_PATH }}/build.binlog

      - id: test
        name: ðŸ§ª Test
        run: dotnet test -bl:${{ env.BINLOG_PATH }}/test.binlog --output Detailed --results-directory ${{ env.TEST_RESULTS }}

      - name: ðŸ“„ Publish test results
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Test Results
          path: ${{ env.TESTRESULTS_PATH }}/*.trx
          reporter: dotnet-trx

      - name: ðŸ“¤ Publish test artifacts
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() && steps.test.outcome != 'skipped' }}
        with:
          name: test-results
          path: ${{ env.TESTRESULTS_PATH }}


      - name: ðŸ“Š ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: '*.coverage'
          targetdir: ${{ env.COVERAGEREPORT_PATH }}
          reporttypes: HtmlInline_AzurePipelines;MarkdownSummaryGithub

      - name: ðŸ“ Publish coverage summary
        run: cat src/target/reports/coverage/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        shell: bash
  
      - name: ðŸ“¤ Publish code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: ${{ env.COVERAGEREPORT_PATH }}         